### PR TITLE
Added import export functionality

### PR DESCRIPTION
**Pull request by alifurkanbudak**
- Saving only OffsetPoints as they're sufficient for reinitialization

### Data Size
I have tested multiple times to check the JSON string's size. On average the SVG export is around 30 kilobytes and the JSON string is about 9 kilobytes.

### Usage Example
```
final control = HandSignatureControl()
[Draw the signature using the UI]
final jsonMap = control.toMap
[Save the jsonMap as you want]
```

On the next launch:
```
final jsonMap  = [load the saved map]
final control = HandSignatureControl.fromMap(jsonMap)
```

### CODE REVIEW

**Comment by RomanBase** [comment]
Hey, this looks better, but you was inspired too much with my test :)
In my test I just want to check if is possible to use only `OffsetPoint`s for export/import so sorry for misleading..

Export structure should be `Map<String, dynamic>` with consistent naming across other export methods `toImage`, `toSvg`. So other users can decide what will do with data - store to DB or convert to json.
And other properties (threshold, smoothing, velocity) should be exported/imported too, because they are used during 'drawing' phase.

**Comment by alifurkanbudak** [comment]
Your test was good enough for my usage :) but you're right. I'll make the necessary changes.

**Comment by alifurkanbudak** [comment]
I made the changes and updated the initial comment.

**Comment by RomanBase** [comment]
Changes will be published in version `2.3.0`.
thx, for contribution..

**Comment by jaypathak9460** [comment]
I am unable to find the solution how can i make signature edit if i have base64string? tried import functionality but unable to convert base 64 to any importable format

**Comment by RomanBase** [comment]
> I am unable to find the solution how can i make signature edit if i have base64string? tried import functionality but unable to convert base 64 to any importable format

Please fill new issue and give us more info what are you trying to achieve. What's in your base64string (json or png)?
To edit data you can import only JSON / Map<String, dynamic>.

**Pull request merged**
